on:
  push:
    branches: [ "master" ]
    paths:
      - #'your-source-path'
  workflow_dispatch:
    inputs: 
      branch_name: 
        required: true
        default: "master"
env: 
  ECR_REPOSITORY: #"your-repository-name"
  ECR_REGISTRY: ${{ secrets.REGISTRY }}
  IMAGE_TAG: ${{ github.run_number }}
  SERVICE_NAME: #"deployment-name"
  CONTAINER_NAME: #"container-name"
  DOCKERFILE: #"Dockerfile Path"
  KUBERNETES_CLUSTER: #"kubernetes name"

name: kubernetes-deployment
jobs:
  build: 
    name: build image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $DOCKERFILE .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4.0.0
      with:
        version: 'v1.30.0'
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Kubectl image change
      run: |
        aws eks update-kubeconfig --region ${{ secrets.REGION }} --name $KUBERNETES_CLUSTER
        kubectl set image deployment/$SERVICE_NAME $CONTAINER_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
