on:
  push:
    branches: [ "master" ]

name: your-service
jobs:
  build: 
    name: build image
    runs-on: ubuntu-latest
    env: 
      ECR_REPOSITORY: "your-repo"
      ECR_REGISTRY: "your-aws-registry"
      IMAGE_TAG: ${{ github.run_number }}
      SERVICE_NAME: "deployment-name"
      CONTAINER_NAME: "deployment-container-name"
      DOCKERFILE: "you dockerfile path"
      EKS_CLUSTER_NAME: "your cluster name"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $DOCKERFILE .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    needs: build
    env: 
      ECR_REPOSITORY: "your-repo"
      ECR_REGISTRY: "your-aws-registry"
      IMAGE_TAG: ${{ github.run_number }}
      SERVICE_NAME: "deployment-name"
      CONTAINER_NAME: "deployment-container-name"
    steps:
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4.0.0
      with:
        version: 'v1.30.0'
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: update kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ secrets.REGION }} --name $EKS_CLUSTER_NAME
        kubectl set image deployment/$SERVICE_NAME $CONTAINER_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
